name: Test official Chia Docker Image

on:
  pull_request:

jobs:
  docker_build:
    runs-on: [Bootstrap]
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const releases = github.repos.listReleases({
              owner: 'Chia-Network',
              repo: 'chia-blockchain',
            });
            console.log(releases);
